name: Test Created Project
workspace: C:\Dev\Projects/testcreatedproject/testcreatedproject.code-workspace
dev_dir: C:\Dev\Projects/testcreatedproject
task_start: dev
apps:
- code
- notion
urls:
- http://localhost:3000
vercel: null
supabase: null
railway: null
