version: '3'
tasks:
  dev:
    desc: Start development server
    cmds:
    - echo 'Starting development server...'
  build:
    desc: Build the project
    cmds:
    - echo 'Building project...'
  test:
    desc: Run tests
    cmds:
    - echo 'Running tests...'
